export const articlesSearchIndex = [
  {
    slug: "melhor-racao-para-pitbull-e-caes-ativos",
    title: "Melhor Ração para Pitbull e Cães Ativos em 2026",
    category: "Alimentação & Ranking",
    description: "Ranking revelando a campeã técnica e a Melhor Compra entre 13 rações analisadas.",
    keywords: ["pitbull", "ração", "ração para pitbull", "cães ativos", "premier", "lunch dog", "x-pro", "nutrição"],
  },
  {
    slug: "alimentacao-saudavel",
    title: "Guia Completo para uma Alimentação Saudável",
    category: "Alimentação",
    description: "Desmistifique a alimentação natural e descubra como alimentar seu pet com saúde e segurança.",
    keywords: ["alimentação natural", "comida saudável", "dieta pet", "nutrição", "saúde"],
  },
  {
    slug: "cuidados-com-pets-no-inverno",
    title: "Cuidados Diários com Cães e Gatos no Inverno",
    category: "Cuidados Diários",
    description: "Saiba como proteger seu pet em temperaturas baixas, agasalhos e banhos no frio.",
    keywords: ["inverno", "frio", "cuidados", "roupinhas", "aquecimento", "banho no frio"],
  },
  {
    slug: "vagas-para-castracao-gratuita",
    title: "Vagas para Castração Gratuita de Cães e Gatos",
    category: "Utilidade Pública",
    description: "Prefeitura abriu milhares de vagas gratuitas de castração municipal.",
    keywords: ["castração", "gratuita", "curitiba", "vagas", "rede de proteção animal", "prefeitura"],
  },
  {
    slug: "alimentacao-saudavel-e-inteligente",
    title: "Guia de Alimentação Responsável e Inteligente",
    category: "Alimentação",
    description: "Passo a passo para dar um alimento seguro, saboroso e equilibrado.",
    keywords: ["alimentação inteligente", "ração responsável", "nutrição pet"],
  },
  {
    slug: "novo-hospital-veterinario-curitiba",
    title: "Novo Hospital Veterinário Municipal em Curitiba",
    category: "Utilidade Pública",
    description: "Conheça o atendimento público veterinário gratuito com mais de 10 mil consultas realizadas.",
    keywords: ["hospital veterinário", "curitiba", "gratuito", "atendimento público", "veterinário"],
  },
  {
    slug: "batata-doce-nutricao-canina",
    title: "Batata Doce e Vegetais na Nutrição Canina",
    category: "Alimentação",
    description: "A batata-doce emergiu como um superalimento seguro para cães.",
    keywords: ["batata doce", "vegetais", "legumes", "nutrição canina", "superalimento"],
  },
  {
    slug: "primeiros-socorros-para-pets",
    title: "Primeiros Socorros para Cães e Gatos: Guia de Emergências",
    category: "Cuidados Diários",
    description: "Saiba como agir em casos de engasgo, intoxicação, acidentes e queimaduras.",
    keywords: ["primeiros socorros", "emergência", "engasgo", "intoxicação", "veterinário 24h"],
  },
  {
    slug: "ferramenta-encontre-seu-pet",
    title: "Ferramenta para Encontrar Pets Perdidos",
    category: "Utilidade Pública",
    description: "RPC lança sistema de localização para reencontrar animais desaparecidos.",
    keywords: ["pet perdido", "cachorro perdido", "gato perdido", "ferramenta", "localização", "rpc"],
  },
  {
    slug: "melhor-racao-para-filhotes",
    title: "Melhor Ração Premium para Filhotes",
    category: "Alimentação",
    description: "Como escolher a melhor ração para o crescimento saudável do filhote.",
    keywords: ["filhote", "ração para filhote", "crescimento", "ração premium"],
  },
  {
    slug: "cupom-petz",
    title: "Cupom de Desconto 10% OFF na Petz",
    category: "Cupons e Promoções",
    description: "Aproveite 10% de desconto com o cupom exclusivo em mais de 20.000 produtos.",
    keywords: ["cupom", "desconto", "petz", "promoção", "oferta", "comprar ração"],
  },
];
